name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - test-ci
      
jobs:
  ci:
    name: Build
    runs-on: windows-latest
    
    steps:
      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4
        
      - uses: actions/checkout@v2
      
      - name: Restore packages
        run: MSBuild.exe -t:restore -p:RestorePackagesConfig=true

      - name: Disable Out of process builds
        run: |
          $env:DisableOutOfProcessBuildPath = "$env:DevEnvDir" + "CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild"
          Test-Path $env:DisableOutOfProcessBuildPath
          if ($env:DisableOutOfProcessBuildPath | Test-Path) {
            cd $env:DisableOutOfProcessBuildPath
            .\DisableOutOfProcBuild.exe
          }
        
      - name: Build the solution
        id: build
        run: |
          pwd
          devenv.com .\CSExeCOMServer.sln /Build Release
