name: Release

on:
  pull_request:
  push:
    branches:
      - master
      - test-ci
    tags:
      - 'v*'
      
jobs:
  ci:
    name: Build
    runs-on: windows-latest
    
    steps:
      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4
        
      - uses: actions/checkout@v2
      
      - name: Restore packages
        run: MSBuild.exe -t:restore -p:RestorePackagesConfig=true

      - name: Disable Out of process builds
        run: |
          $env:DisableOutOfProcessBuildPath = "$env:DevEnvDir" + "CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild"
          if ($env:DisableOutOfProcessBuildPath | Test-Path) {
            cd $env:DisableOutOfProcessBuildPath
            .\DisableOutOfProcBuild.exe
          }
        
      - name: Build the solution
        run: devenv.com .\CSExeCOMServer.sln /Build Release

      - name: Remove files and create a zip of the build
        run: |
          if (Test-Path .\MattermostPresenceProvider\Debug\) { Remove-Item .\MattermostPresenceProvider\Debug\ -Recurse }
          if (Test-Path .\MattermostPresenceProvider\Release\) { Remove-Item .\MattermostPresenceProvider\Release\ -Recurse }
          if (Test-Path .\MattermostPresenceProvider\MattermostPresenceProvider.vdproj) { Remove-Item .\MattermostPresenceProvider\MattermostPresenceProvider.vdproj }
          Compress-Archive -Path .\MattermostPresenceProvider\ -DestinationPath MattermostPresenceProvider.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 0.1.0
          release_name: Release 0.1.0
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./MattermostPresenceProvider.zip
          asset_name: MattermostPresenceProvider.zip
          asset_content_type: application/gzip
